2019-08-25 11:50:25,417 ERROR 42978 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:189:13)
    at Handshake._onTimeout (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Timer.js:32:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    --------------------
    at Protocol._enqueue (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:48:16)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:56:34)
    at Pool.query (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:202:8)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 42978
hostname: localhost

2019-08-25 11:50:45,151 ERROR 42980 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:189:13)
    at Handshake._onTimeout (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Timer.js:32:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    --------------------
    at Protocol._enqueue (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:48:16)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:56:34)
    at Pool.query (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:202:8)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 42980
hostname: localhost

2019-08-25 11:55:22,246 ERROR 43042 [-/127.0.0.1/-/1ms GET /] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Connection.js:412:13)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    --------------------
    at Protocol._enqueue (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:48:16)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:56:34)
    at Pool.query (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:202:8)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    sql: select now() as currentTime;
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 43042
hostname: localhost

2019-08-25 11:56:11,046 ERROR 43044 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:189:13)
    at Handshake._onTimeout (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Timer.js:32:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    --------------------
    at Protocol._enqueue (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:48:16)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:56:34)
    at Pool.query (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_mysql@2.17.1@mysql/lib/Pool.js:202:8)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/_pify@2.3.0@pify/index.js:29:7
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 43044
hostname: localhost

2019-08-25 12:00:16,128 ERROR 43361 [-/::1/-/4ms GET /login] nodejs.TypeError: this.ctx.service.user.login is not a function
    at UserController.login (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/app/controller/user.js:6:47)
    at Object.callFn (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/koa-compose/index.js:44:32)
    at next (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/koa-compose/index.js:45:18)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/koa-compose/index.js:44:32)
    at /Users/icourt/Documents/project/fuko/fake_meid_recognition_node/node_modules/koa-compose/index.js:36:12

pid: 43361
hostname: localhost

